export const latinAmericanCountries = [
    { nameOfCountry: "Argentina", codeOfCountry: "+54" },
    { nameOfCountry: "Bolivia", codeOfCountry: "+591" },
    { nameOfCountry: "Brazil", codeOfCountry: "+55" },
    { nameOfCountry: "Chile", codeOfCountry: "+56" },
    { nameOfCountry: "Colombia", codeOfCountry: "+57" },
    { nameOfCountry: "Costa Rica", codeOfCountry: "+506" },
    { nameOfCountry: "Cuba", codeOfCountry: "+53" },
    { nameOfCountry: "Dominican Republic", codeOfCountry: "+1" },
    { nameOfCountry: "Ecuador", codeOfCountry: "+593" },
    { nameOfCountry: "El Salvador", codeOfCountry: "+503" },
    { nameOfCountry: "Guatemala", codeOfCountry: "+502" },
    { nameOfCountry: "Honduras", codeOfCountry: "+504" },
    { nameOfCountry: "Mexico", codeOfCountry: "+52" },
    { nameOfCountry: "Nicaragua", codeOfCountry: "+505" },
    { nameOfCountry: "Panama", codeOfCountry: "+507" },
    { nameOfCountry: "Paraguay", codeOfCountry: "+595" },
    { nameOfCountry: "Peru", codeOfCountry: "+51" },
    { nameOfCountry: "Puerto Rico", codeOfCountry: "+1" },
    { nameOfCountry: "Uruguay", codeOfCountry: "+598" },
    { nameOfCountry: "Venezuela", codeOfCountry: "+58" },
    { nameOfCountry: "Belize", codeOfCountry: "+501" },
    { nameOfCountry: "Guyana", codeOfCountry: "+592" },
    { nameOfCountry: "Suriname", codeOfCountry: "+597" },
    { nameOfCountry: "Trinidad and Tobago", codeOfCountry: "+1" },
    { nameOfCountry: "Haiti", codeOfCountry: "+509" },
    { nameOfCountry: "Jamaica", codeOfCountry: "+1" },
    { nameOfCountry: "Barbados", codeOfCountry: "+1" },
    { nameOfCountry: "Antigua and Barbuda", codeOfCountry: "+1" },
    { nameOfCountry: "Grenada", codeOfCountry: "+1" },
    { nameOfCountry: "Saint Lucia", codeOfCountry: "+1" },
    { nameOfCountry: "Saint Vincent and the Grenadines", codeOfCountry: "+1" }
];

export const clientObject = {
    name: '',
    lastName: '',
    celPhone: '',
    email: '',
    dateOfBirth: ''
}
